## Numpy

In [ ]:
import numpy as np

1. Create an `ndarray` of shape (3,5). All values of the array are 100.

In [ ]:
x = np.ones((3, 5)) * 100
x

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

2. Create a border of zeros that surround the result in Question 1, so that the output is of shape (5,7), the outside values are 0 and the inside values are 100. 

In [ ]:
np.pad(x, pad_width=1)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])

3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.


In [ ]:
np.diag(np.arange(4) + 1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

4. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
np.tile(np.vstack([np.tile([1, 0], 4), np.tile([0, 1], 4)]), (4, 1))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

5. Sort a 2d-array by the nth column

In [ ]:
arr = np.hstack([np.random.rand(12)]).reshape(-1, 3)
print(arr)
np.sort(arr.view('f8,f8,f8'), order=['f1'], axis=0)

[[0.12263971 0.29665541 0.94511153]
 [0.98280729 0.50925414 0.15228416]
 [0.68650034 0.16268925 0.36155802]
 [0.09148439 0.92177628 0.89505899]]


array([[(0.68650034, 0.16268925, 0.36155802)],
       [(0.12263971, 0.29665541, 0.94511153)],
       [(0.98280729, 0.50925414, 0.15228416)],
       [(0.09148439, 0.92177628, 0.89505899)]],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8')])

6. Compute a matrix rank

In [ ]:
m = np.matrix(np.random.rand(9).reshape(-1, 3))
print(m)
np.linalg.matrix_rank(m)

[[0.11926021 0.8775477  0.98240132]
 [0.21132579 0.40884896 0.33548589]
 [0.58789874 0.60144223 0.09697618]]


3

7. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [ ]:
x = np.arange(5 * 5 * 3).reshape(5, 5, 3)
y = np.arange(5 * 5).reshape(5, -1)
print(f'x = {x}, y = {y}')
x * y.reshape(5, 5, 1)

x = [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]], y = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[[   0,    0,    0],
        [   3,    4,    5],
        [  12,   14,   16],
        [  27,   30,   33],
        [  48,   52,   56]],

       [[  75,   80,   85],
        [ 108,  114,  120],
        [ 147,  154,  161],
        [ 192,  200,  208],
        [ 243,  252,  261]],

       [[ 300,  310,  320],
        [ 363,  374,  385],
        [ 432,  444,  456],
        [ 507,  520,  533],
        [ 588,  602,  616]],

       [[ 675,  690,  705],
        [ 768,  784,  800],
        [ 867,  884,  901],
        [ 972,  990, 1008],
        [1083, 1102, 1121]],

       [[1200, 1220, 1240],
        [1323, 1344, 1365],
        [1452, 1474, 1496],
        [1587, 1610, 1633],
        [1728, 1752, 1776]]])

8. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [ ]:
# x = np.ones((16, 16))
x = np.arange(16 * 16).reshape(16, 16)
print(x)
k = 4
np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0), np.arange(0, x.shape[1], k), axis=1)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

9. Get the n largest values of an array

In [ ]:
x = np.arange(10, 1, -1)
print(f'x = {x}')
sorted_indices = np.argsort(x)

n = 3
x[sorted_indices[-n:]]

x = [10  9  8  7  6  5  4  3  2]


array([ 8,  9, 10])

10. Implement the Game of Life using numpy arrays

In [ ]:
class Status:
  EMPTY = 0
  ALIVE = 1

class Grid:
  def __init__(self, height, width):
    self.height = height
    self.width = width
    self.grid = np.zeros((height, width))

  def get(self, x, y):
    return self.grid[x % self.height, y % self.width]

  def set(self, x, y, state):
    self.grid[x % self.height, y % self.width] = state


def count_neighbors(x, y, get):
  ds = [[0, 1], [0, -1], [1, 0], [-1, 0], [1, 1], [1, -1], [-1, 1], [-1, -1]]
  state = np.sum([get(x + d[0], y + d[1]) for d in ds])
  return state


def game_logic(state, neighbors):
  if state == Status.ALIVE:
    if neighbors < 2 or neighbors > 3:
      return Status.EMPTY

  else:
    if neighbors == 3:
      return Status.ALIVE
  return state


def step_cell(x, y, get, set):
  state = get(x, y)
  neighbors = count_neighbors(x, y, get)
  next_state = game_logic(state, neighbors)
  set(x, y, next_state)


def simulate(grid):
  next_grid = Grid(grid.height, grid.width)
  for x in range(grid.height):
    for y in range(grid.width):
      step_cell(x, y, grid.get, next_grid.set)
  return next_grid

Check https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb for more Numpy exercises.

## Pandas

In [ ]:
import pandas as pd
import seaborn as sb

1. Using NumPy, create a Pandas DataFrame with five rows and three columns

In [ ]:
pd.DataFrame(np.ones((5, 3)))

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0

The following six questions depend on the penguins dataset.

In [ ]:
df_penguins = sb.load_dataset('penguins')

2. What function can we use to drop the rows that have missing data?

In [ ]:
df_full = df_penguins.dropna(axis=0, how='any')
df_full

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[333 rows x 7 columns]

3. By default, will the function in Question 2 modify df_penguins or will it return a copy?

by default it will return a copy

4. Let df_full be the dataframe obtained from dropping rows with missing data. What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [ ]:
df_full['bill_length_mm'].mean()

43.99279279279279

5. Which species has the longest flippers?

In [ ]:
idx = df_full['flipper_length_mm'].idxmax()
df_full.loc[idx, 'species']

'Gentoo'

6. Which two species have the most similar mean weight?

In [ ]:
info = df_full.groupby('species')['body_mass_g'].mean().to_dict()
print(f'info = {info}')

diff = np.infty
arg_x = arg_y = None
for x, wx in info.items():
  for y, wy in info.items():
    if x == y: continue

    curr_diff = np.abs(wx - wy)
    if curr_diff < diff:
      arg_x, arg_y = x , y
      diff = curr_diff

print(f'species {arg_x} and {arg_y} have the most similar mean weight.')

info = {'Adelie': 3706.1643835616437, 'Chinstrap': 3733.0882352941176, 'Gentoo': 5092.436974789916}
species Adelie and Chinstrap have the most similar mean weight.


7. How could you sort by species first, then by body mass?

In [ ]:
df_full.sort_values(by=['species', 'body_mass_g'])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   
..      ...        ...             ...            ...                ...   
331  Gentoo     Biscoe            49.8           15.9              229.0   
297  Gentoo     Biscoe            51.1           16.3              220.0   
337  Gentoo     Biscoe            48.8           16.2              222.0   
253  Gentoo     Biscoe            59.6           17.0              230.0   
237  Gentoo     Biscoe            49.2           15.2              221.0   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
331       5950.0    Male  
297       6000.0    Male  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  

[333 rows x 7 columns]

The following three questions depend on the taxis dataset.

In [ ]:
df_taxis = sb.load_dataset('taxis')

8. The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [ ]:
df_taxis = df_taxis.assign(pickup_time=pd.to_datetime(df_taxis['pickup']))

9. Create a subset of the dataframe to create a new DataFrame, taxis_one_day. This new DataFrame should have pickup_time values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [ ]:
start_time = pd.to_datetime('2019-03-23 00:06:00')
end_time = pd.to_datetime('2019-03-24 00:00:00')
taxis_one_day = df_taxis[(df_taxis['pickup_time'] >= start_time) & (df_taxis['pickup_time'] < end_time)]

10. From the dataframe in Question 9, take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

In [ ]:
tmp_df = taxis_one_day.assign(hour=taxis_one_day['pickup_time'].apply(lambda x : x.hour))
df_means = tmp_df.drop(columns=['pickup_time']).groupby('hour').mean()
df_means

passengers  distance       fare       tip     tolls      total
hour                                                                
0       1.000000  1.911667   8.583333  1.415000  0.000000  12.965000
1       1.250000  1.325000   7.875000  1.525000  0.000000  12.575000
2       1.727273  1.739091   8.181818  1.641818  0.000000  13.169091
3       1.500000  3.377500  11.750000  2.410000  0.000000  17.335000
4       2.000000  0.950000   5.500000  0.915000  0.000000  10.215000
5       2.000000  1.270000   6.000000  0.980000  0.000000  10.530000
6       1.000000  0.400000  21.500000  0.000000  0.000000  23.133333
7       2.333333  0.980000   5.250000  1.165000  0.000000   9.298333
8       1.000000  0.020000   2.500000  0.000000  0.000000   3.300000
9       1.500000  1.352000   7.400000  1.674000  0.000000  12.124000
10      1.000000  1.760000   8.750000  0.727500  0.000000  12.152500
11      1.909091  2.070000  11.090909  0.803636  0.000000  14.667273
12      2.000000  2.267143  10.260000  0.645714  0.000000  13.420000
13      2.500000  1.167000   7.550000  2.074000  0.000000  12.344000
14      2.470588  4.752941  18.330000  1.945294  1.003529  24.267059
15      1.000000  6.557143  22.214286  3.210000  1.645714  30.370000
16      2.000000  2.194545  10.454545  1.109091  0.000000  14.431818
17      1.090909  1.913636  14.818182  2.688182  0.523636  20.739091
18      1.571429  3.206429  12.821429  0.844286  0.411429  16.427143
19      1.526316  2.097895  10.263158  1.176316  0.000000  14.226316
20      1.400000  2.448000  11.100000  1.544000  0.000000  15.944000
21      1.000000  2.017143  10.571429  1.420000  0.000000  15.791429
22      1.307692  1.881538   8.923077  1.094615  0.000000  13.433077
23      1.615385  3.725385  15.115385  1.696154  0.000000  20.034615

Check https://colab.research.google.com/github/CodeSolid/CodeSolid.github.io/blob/main/booksource/exercises/PandasExercises.ipynb for more Pandas exercises.